//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen schema.xsd --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.List`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Products
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemType", Namespace = "http://cpe.mitre.org/dictionary/2.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("cpe-item", Namespace = "http://cpe.mitre.org/dictionary/2.0")]
    public partial class NvdCpeItem
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NvdCpeTitle> _title;

        [System.Xml.Serialization.XmlElementAttribute("title")]
        public System.Collections.Generic.List<NvdCpeTitle> Title
        {
            get
            {
                return this._title;
            }
            private set
            {
                this._title = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TitleSpecified
        {
            get
            {
                return (this.Title.Count != 0);
            }
        }

        public NvdCpeItem()
        {
            this._title = new System.Collections.Generic.List<NvdCpeTitle>();
            this._references = new System.Collections.Generic.List<NvdCpeReference>();
            this._any = new System.Collections.Generic.List<System.Xml.XmlElement>();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NvdCpeReference> _references;

        [System.Xml.Serialization.XmlArrayAttribute("references")]
        [System.Xml.Serialization.XmlArrayItemAttribute("reference", Namespace = "http://cpe.mitre.org/dictionary/2.0")]
        public System.Collections.Generic.List<NvdCpeReference> References
        {
            get
            {
                return this._references;
            }
            private set
            {
                this._references = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencesSpecified
        {
            get
            {
                return (this.References.Count != 0);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<System.Xml.XmlElement> _any;

        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.Generic.List<System.Xml.XmlElement> Any
        {
            get
            {
                return this._any;
            }
            private set
            {
                this._any = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AnySpecified
        {
            get
            {
                return (this.Any.Count != 0);
            }
        }

        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\\._\\-~%]*){0,6}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
#nullable disable
        public string Name { get; set; }
#nullable restore

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _deprecated = false;

        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("deprecated")]
        public bool Deprecated
        {
            get
            {
                return this._deprecated;
            }
            set
            {
                this._deprecated = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("deprecation_date", DataType = "dateTime")]
        public System.DateTime Deprecation_Date { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Deprecation_DateSpecified { get; set; }
    }
}
