//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("WeaknessType", Namespace="http://cwe.mitre.org/cwe-6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MitreCweWeaknessType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Extended_Description")]
        public MitreCweStructuredTextType Extended_Description { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweRelatedWeaknessesTypeRelated_Weakness> _related_Weaknesses;
        
        [System.Xml.Serialization.XmlArrayAttribute("Related_Weaknesses")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Related_Weakness", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweRelatedWeaknessesTypeRelated_Weakness> Related_Weaknesses
        {
            get
            {
                return this._related_Weaknesses;
            }
            private set
            {
                this._related_Weaknesses = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Related_WeaknessesSpecified
        {
            get
            {
                return (this.Related_Weaknesses.Count != 0);
            }
        }
        
        public MitreCweWeaknessType()
        {
            this._related_Weaknesses = new System.Collections.Generic.List<MitreCweMitreCweRelatedWeaknessesTypeRelated_Weakness>();
            this._weakness_Ordinalities = new System.Collections.Generic.List<MitreCweMitreCweWeaknessOrdinalitiesTypeWeakness_Ordinality>();
            this._background_Details = new System.Collections.Generic.List<MitreCweStructuredTextType>();
            this._alternate_Terms = new System.Collections.Generic.List<MitreCweMitreCweAlternateTermsTypeAlternate_Term>();
            this._modes_Of_Introduction = new System.Collections.Generic.List<MitreCweMitreCweModesOfIntroductionTypeIntroduction>();
            this._exploitation_Factors = new System.Collections.Generic.List<MitreCweStructuredTextType>();
            this._common_Consequences = new System.Collections.Generic.List<MitreCweMitreCweCommonConsequencesTypeConsequence>();
            this._detection_Methods = new System.Collections.Generic.List<MitreCweMitreCweDetectionMethodsTypeDetection_Method>();
            this._potential_Mitigations = new System.Collections.Generic.List<MitreCweMitreCwePotentialMitigationsTypeMitigation>();
            this._demonstrative_Examples = new System.Collections.Generic.List<MitreCweMitreCweDemonstrativeExamplesTypeDemonstrative_Example>();
            this._observed_Examples = new System.Collections.Generic.List<MitreCweMitreCweObservedExampleTypeObserved_Example>();
            this._functional_Areas = new System.Collections.Generic.List<MitreCweFunctionalAreaEnumeration>();
            this._affected_Resources = new System.Collections.Generic.List<MitreCweResourceEnumeration>();
            this._taxonomy_Mappings = new System.Collections.Generic.List<MitreCweMitreCweTaxonomyMappingsTypeTaxonomy_Mapping>();
            this._related_Attack_Patterns = new System.Collections.Generic.List<MitreCweMitreCweRelatedAttackPatternsTypeRelated_Attack_Pattern>();
            this._references = new System.Collections.Generic.List<MitreCweMitreCweReferencesTypeReference>();
            this._notes = new System.Collections.Generic.List<MitreCweMitreCweNotesTypeNote>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweWeaknessOrdinalitiesTypeWeakness_Ordinality> _weakness_Ordinalities;
        
        [System.Xml.Serialization.XmlArrayAttribute("Weakness_Ordinalities")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Weakness_Ordinality", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweWeaknessOrdinalitiesTypeWeakness_Ordinality> Weakness_Ordinalities
        {
            get
            {
                return this._weakness_Ordinalities;
            }
            private set
            {
                this._weakness_Ordinalities = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Weakness_OrdinalitiesSpecified
        {
            get
            {
                return (this.Weakness_Ordinalities.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Applicable_Platforms")]
        public MitreCweApplicablePlatformsType Applicable_Platforms { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweStructuredTextType> _background_Details;
        
        [System.Xml.Serialization.XmlArrayAttribute("Background_Details")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Background_Detail", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweStructuredTextType> Background_Details
        {
            get
            {
                return this._background_Details;
            }
            private set
            {
                this._background_Details = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Background_DetailsSpecified
        {
            get
            {
                return (this.Background_Details.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweAlternateTermsTypeAlternate_Term> _alternate_Terms;
        
        [System.Xml.Serialization.XmlArrayAttribute("Alternate_Terms")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Alternate_Term", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweAlternateTermsTypeAlternate_Term> Alternate_Terms
        {
            get
            {
                return this._alternate_Terms;
            }
            private set
            {
                this._alternate_Terms = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Alternate_TermsSpecified
        {
            get
            {
                return (this.Alternate_Terms.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweModesOfIntroductionTypeIntroduction> _modes_Of_Introduction;
        
        [System.Xml.Serialization.XmlArrayAttribute("Modes_Of_Introduction")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Introduction", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweModesOfIntroductionTypeIntroduction> Modes_Of_Introduction
        {
            get
            {
                return this._modes_Of_Introduction;
            }
            private set
            {
                this._modes_Of_Introduction = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Modes_Of_IntroductionSpecified
        {
            get
            {
                return (this.Modes_Of_Introduction.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweStructuredTextType> _exploitation_Factors;
        
        [System.Xml.Serialization.XmlArrayAttribute("Exploitation_Factors")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Exploitation_Factor", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweStructuredTextType> Exploitation_Factors
        {
            get
            {
                return this._exploitation_Factors;
            }
            private set
            {
                this._exploitation_Factors = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Exploitation_FactorsSpecified
        {
            get
            {
                return (this.Exploitation_Factors.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Likelihood_Of_Exploit")]
        public MitreCweLikelihoodEnumeration Likelihood_Of_Exploit { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Likelihood_Of_ExploitSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweCommonConsequencesTypeConsequence> _common_Consequences;
        
        [System.Xml.Serialization.XmlArrayAttribute("Common_Consequences")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Consequence", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweCommonConsequencesTypeConsequence> Common_Consequences
        {
            get
            {
                return this._common_Consequences;
            }
            private set
            {
                this._common_Consequences = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Common_ConsequencesSpecified
        {
            get
            {
                return (this.Common_Consequences.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweDetectionMethodsTypeDetection_Method> _detection_Methods;
        
        [System.Xml.Serialization.XmlArrayAttribute("Detection_Methods")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Detection_Method", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweDetectionMethodsTypeDetection_Method> Detection_Methods
        {
            get
            {
                return this._detection_Methods;
            }
            private set
            {
                this._detection_Methods = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Detection_MethodsSpecified
        {
            get
            {
                return (this.Detection_Methods.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCwePotentialMitigationsTypeMitigation> _potential_Mitigations;
        
        [System.Xml.Serialization.XmlArrayAttribute("Potential_Mitigations")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Mitigation", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCwePotentialMitigationsTypeMitigation> Potential_Mitigations
        {
            get
            {
                return this._potential_Mitigations;
            }
            private set
            {
                this._potential_Mitigations = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Potential_MitigationsSpecified
        {
            get
            {
                return (this.Potential_Mitigations.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweDemonstrativeExamplesTypeDemonstrative_Example> _demonstrative_Examples;
        
        [System.Xml.Serialization.XmlArrayAttribute("Demonstrative_Examples")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Demonstrative_Example", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweDemonstrativeExamplesTypeDemonstrative_Example> Demonstrative_Examples
        {
            get
            {
                return this._demonstrative_Examples;
            }
            private set
            {
                this._demonstrative_Examples = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Demonstrative_ExamplesSpecified
        {
            get
            {
                return (this.Demonstrative_Examples.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweObservedExampleTypeObserved_Example> _observed_Examples;
        
        [System.Xml.Serialization.XmlArrayAttribute("Observed_Examples")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Observed_Example", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweObservedExampleTypeObserved_Example> Observed_Examples
        {
            get
            {
                return this._observed_Examples;
            }
            private set
            {
                this._observed_Examples = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Observed_ExamplesSpecified
        {
            get
            {
                return (this.Observed_Examples.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweFunctionalAreaEnumeration> _functional_Areas;
        
        [System.Xml.Serialization.XmlArrayAttribute("Functional_Areas")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Functional_Area", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweFunctionalAreaEnumeration> Functional_Areas
        {
            get
            {
                return this._functional_Areas;
            }
            private set
            {
                this._functional_Areas = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Functional_AreasSpecified
        {
            get
            {
                return (this.Functional_Areas.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweResourceEnumeration> _affected_Resources;
        
        [System.Xml.Serialization.XmlArrayAttribute("Affected_Resources")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Affected_Resource", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweResourceEnumeration> Affected_Resources
        {
            get
            {
                return this._affected_Resources;
            }
            private set
            {
                this._affected_Resources = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Affected_ResourcesSpecified
        {
            get
            {
                return (this.Affected_Resources.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweTaxonomyMappingsTypeTaxonomy_Mapping> _taxonomy_Mappings;
        
        [System.Xml.Serialization.XmlArrayAttribute("Taxonomy_Mappings")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Taxonomy_Mapping", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweTaxonomyMappingsTypeTaxonomy_Mapping> Taxonomy_Mappings
        {
            get
            {
                return this._taxonomy_Mappings;
            }
            private set
            {
                this._taxonomy_Mappings = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Taxonomy_MappingsSpecified
        {
            get
            {
                return (this.Taxonomy_Mappings.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweRelatedAttackPatternsTypeRelated_Attack_Pattern> _related_Attack_Patterns;
        
        [System.Xml.Serialization.XmlArrayAttribute("Related_Attack_Patterns")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Related_Attack_Pattern", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweRelatedAttackPatternsTypeRelated_Attack_Pattern> Related_Attack_Patterns
        {
            get
            {
                return this._related_Attack_Patterns;
            }
            private set
            {
                this._related_Attack_Patterns = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Related_Attack_PatternsSpecified
        {
            get
            {
                return (this.Related_Attack_Patterns.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweReferencesTypeReference> _references;
        
        [System.Xml.Serialization.XmlArrayAttribute("References")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Reference", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweReferencesTypeReference> References
        {
            get
            {
                return this._references;
            }
            private set
            {
                this._references = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencesSpecified
        {
            get
            {
                return (this.References.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweNotesTypeNote> _notes;
        
        [System.Xml.Serialization.XmlArrayAttribute("Notes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Note", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweNotesTypeNote> Notes
        {
            get
            {
                return this._notes;
            }
            private set
            {
                this._notes = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotesSpecified
        {
            get
            {
                return (this.Notes.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Content_History")]
        public MitreCweContentHistoryType Content_History { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID")]
        public string ID { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Abstraction")]
        public MitreCweAbstractionEnumeration Abstraction { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Structure")]
        public MitreCweStructureEnumeration Structure { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Status")]
        public MitreCweStatusEnumeration Status { get; set; }
    }
}
