//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MitreCweDemonstrativeExamplesTypeDemonstrative_Example", Namespace="http://cwe.mitre.org/cwe-6", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MitreCweMitreCweDemonstrativeExamplesTypeDemonstrative_Example
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Title_Text")]
        public string Title_Text { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Intro_Text")]
        public MitreCweStructuredTextType Intro_Text { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweStructuredTextType> _body_Text;
        
        [System.Xml.Serialization.XmlElementAttribute("Body_Text")]
        public System.Collections.Generic.List<MitreCweStructuredTextType> Body_Text
        {
            get
            {
                return this._body_Text;
            }
            private set
            {
                this._body_Text = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Body_TextSpecified
        {
            get
            {
                return (this.Body_Text.Count != 0);
            }
        }
        
        public MitreCweMitreCweDemonstrativeExamplesTypeDemonstrative_Example()
        {
            this._body_Text = new System.Collections.Generic.List<MitreCweStructuredTextType>();
            this._example_Code = new System.Collections.Generic.List<MitreCweStructuredCodeType>();
            this._references = new System.Collections.Generic.List<MitreCweMitreCweReferencesTypeReference>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweStructuredCodeType> _example_Code;
        
        [System.Xml.Serialization.XmlElementAttribute("Example_Code")]
        public System.Collections.Generic.List<MitreCweStructuredCodeType> Example_Code
        {
            get
            {
                return this._example_Code;
            }
            private set
            {
                this._example_Code = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Example_CodeSpecified
        {
            get
            {
                return (this.Example_Code.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweReferencesTypeReference> _references;
        
        [System.Xml.Serialization.XmlArrayAttribute("References")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Reference", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweMitreCweReferencesTypeReference> References
        {
            get
            {
                return this._references;
            }
            private set
            {
                this._references = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencesSpecified
        {
            get
            {
                return (this.References.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Demonstrative_Example_ID")]
        public string Demonstrative_Example_ID { get; set; }
    }
}
