//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MitreCweContentHistoryTypeModification", Namespace="http://cwe.mitre.org/cwe-6", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MitreCweMitreCweContentHistoryTypeModification
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Modification_Name")]
        public string Modification_Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Modification_Organization")]
        public string Modification_Organization { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Modification_Date", DataType="date")]
        public System.DateTime Modification_Date { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Modification_DateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Modification_Importance")]
        public MitreCweImportanceEnumeration Modification_Importance { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Modification_ImportanceSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Modification_Comment")]
        public string Modification_Comment { get; set; }
    }
}
