//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LanguageNameEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCweLanguageNameEnumeration
    {
        
        Ada,
        
        ASP,
        
        [System.Xml.Serialization.XmlEnumAttribute("ASP.NET")]
        ASPPeriodNET,
        
        Basic,
        
        C,
        
        [System.Xml.Serialization.XmlEnumAttribute("C++")]
        CPlusPlus,
        
        [System.Xml.Serialization.XmlEnumAttribute("C#")]
        CHash,
        
        COBOL,
        
        Fortran,
        
        [System.Xml.Serialization.XmlEnumAttribute("F#")]
        FHash,
        
        Go,
        
        HTML,
        
        Java,
        
        JavaScript,
        
        JSP,
        
        [System.Xml.Serialization.XmlEnumAttribute("Objective-C")]
        Objective_C,
        
        Pascal,
        
        Perl,
        
        PHP,
        
        Python,
        
        Ruby,
        
        Rust,
        
        Shell,
        
        SQL,
        
        Swift,
        
        [System.Xml.Serialization.XmlEnumAttribute("VB.NET")]
        VBPeriodNET,
        
        Verilog,
        
        VHDL,
        
        XML,
        
        Other,
    }
}
