//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MitigationStrategyEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCweMitigationStrategyEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("Attack Surface Reduction")]
        Attack_Surface_Reduction,
        
        [System.Xml.Serialization.XmlEnumAttribute("Compilation or Build Hardening")]
        Compilation_Or_Build_Hardening,
        
        [System.Xml.Serialization.XmlEnumAttribute("Enforcement by Conversion")]
        Enforcement_By_Conversion,
        
        [System.Xml.Serialization.XmlEnumAttribute("Environment Hardening")]
        Environment_Hardening,
        
        Firewall,
        
        [System.Xml.Serialization.XmlEnumAttribute("Input Validation")]
        Input_Validation,
        
        [System.Xml.Serialization.XmlEnumAttribute("Language Selection")]
        Language_Selection,
        
        [System.Xml.Serialization.XmlEnumAttribute("Libraries or Frameworks")]
        Libraries_Or_Frameworks,
        
        [System.Xml.Serialization.XmlEnumAttribute("Resource Limitation")]
        Resource_Limitation,
        
        [System.Xml.Serialization.XmlEnumAttribute("Output Encoding")]
        Output_Encoding,
        
        Parameterization,
        
        Refactoring,
        
        [System.Xml.Serialization.XmlEnumAttribute("Sandbox or Jail")]
        Sandbox_Or_Jail,
        
        [System.Xml.Serialization.XmlEnumAttribute("Separation of Privilege")]
        Separation_Of_Privilege,
    }
}
