//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TechnologyClassEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCweTechnologyClassEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("Client Server")]
        Client_Server,
        
        [System.Xml.Serialization.XmlEnumAttribute("Cloud Computing")]
        Cloud_Computing,
        
        Mainframe,
        
        Mobile,
        
        [System.Xml.Serialization.XmlEnumAttribute("N-Tier")]
        N_Tier,
        
        SOA,
        
        [System.Xml.Serialization.XmlEnumAttribute("System on Chip")]
        System_On_Chip,
        
        [System.Xml.Serialization.XmlEnumAttribute("Web Based")]
        Web_Based,
        
        [System.Xml.Serialization.XmlEnumAttribute("Technology-Independent")]
        Technology_Independent,
    }
}
