//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PhaseEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCwePhaseEnumeration
    {
        
        Policy,
        
        Requirements,
        
        [System.Xml.Serialization.XmlEnumAttribute("Architecture and Design")]
        Architecture_And_Design,
        
        Implementation,
        
        [System.Xml.Serialization.XmlEnumAttribute("Build and Compilation")]
        Build_And_Compilation,
        
        Testing,
        
        Documentation,
        
        Bundling,
        
        Distribution,
        
        Installation,
        
        [System.Xml.Serialization.XmlEnumAttribute("System Configuration")]
        System_Configuration,
        
        Operation,
        
        [System.Xml.Serialization.XmlEnumAttribute("Patching and Maintenance")]
        Patching_And_Maintenance,
        
        Porting,
        
        Integration,
        
        Manufacturing,
    }
}
