//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TechnologyNameEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCweTechnologyNameEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("Web Server")]
        Web_Server,
        
        [System.Xml.Serialization.XmlEnumAttribute("Database Server")]
        Database_Server,
        
        [System.Xml.Serialization.XmlEnumAttribute("Accelerator Hardware")]
        Accelerator_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Analog and Mixed Signal Hardware")]
        Analog_And_Mixed_Signal_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Audio/Video Hardware")]
        AudioSlashVideo_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Bus/Interface Hardware")]
        BusSlashInterface_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Clock/Counter Hardware")]
        ClockSlashCounter_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Communication Hardware")]
        Communication_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Controller Hardware")]
        Controller_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Memory Hardware")]
        Memory_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Microcontroller Hardware")]
        Microcontroller_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Network on Chip Hardware")]
        Network_On_Chip_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Power Management Hardware")]
        Power_Management_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Processor Hardware")]
        Processor_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Security Hardware")]
        Security_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Sensor Hardware")]
        Sensor_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Storage Hardware")]
        Storage_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Test/Debug Hardware")]
        TestSlashDebug_Hardware,
        
        [System.Xml.Serialization.XmlEnumAttribute("Accelerator IP Hardware")]
        Accelerator_IP_Hardware,
        
        Accelerator,
        
        [System.Xml.Serialization.XmlEnumAttribute("Analog and Mixed Signal IP")]
        Analog_And_Mixed_Signal_IP,
        
        [System.Xml.Serialization.XmlEnumAttribute("Analog and Mixed Signal")]
        Analog_And_Mixed_Signal,
        
        [System.Xml.Serialization.XmlEnumAttribute("Audio/Video IP")]
        AudioSlashVideo_IP,
        
        [System.Xml.Serialization.XmlEnumAttribute("Audio/Video")]
        AudioSlashVideo,
        
        [System.Xml.Serialization.XmlEnumAttribute("Bus/Interface IP")]
        BusSlashInterface_IP,
        
        [System.Xml.Serialization.XmlEnumAttribute("Bus/Interface")]
        BusSlashInterface,
        
        [System.Xml.Serialization.XmlEnumAttribute("Clock/Counter IP")]
        ClockSlashCounter_IP,
        
        [System.Xml.Serialization.XmlEnumAttribute("Clock/Counter")]
        ClockSlashCounter,
        
        [System.Xml.Serialization.XmlEnumAttribute("Communication IP")]
        Communication_IP,
        
        Communication,
        
        [System.Xml.Serialization.XmlEnumAttribute("Controller IP")]
        Controller_IP,
        
        Controller,
        
        [System.Xml.Serialization.XmlEnumAttribute("Memory IP")]
        Memory_IP,
        
        Memory,
        
        [System.Xml.Serialization.XmlEnumAttribute("Microcontroller IP")]
        Microcontroller_IP,
        
        Microcontroller,
        
        [System.Xml.Serialization.XmlEnumAttribute("Network on Chip IP")]
        Network_On_Chip_IP,
        
        [System.Xml.Serialization.XmlEnumAttribute("Network on Chip")]
        Network_On_Chip,
        
        [System.Xml.Serialization.XmlEnumAttribute("Power Management IP")]
        Power_Management_IP,
        
        [System.Xml.Serialization.XmlEnumAttribute("Power Management")]
        Power_Management,
        
        [System.Xml.Serialization.XmlEnumAttribute("Processor IP")]
        Processor_IP,
        
        Processor,
        
        [System.Xml.Serialization.XmlEnumAttribute("Security IP")]
        Security_IP,
        
        Security,
        
        [System.Xml.Serialization.XmlEnumAttribute("Sensor IP")]
        Sensor_IP,
        
        Sensor,
        
        [System.Xml.Serialization.XmlEnumAttribute("Storage IP")]
        Storage_IP,
        
        Storage,
        
        [System.Xml.Serialization.XmlEnumAttribute("Test/Debug IP")]
        TestSlashDebug_IP,
        
        [System.Xml.Serialization.XmlEnumAttribute("Test/Debug")]
        TestSlashDebug,
        
        Other,
    }
}
