//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ContentHistoryType", Namespace="http://cwe.mitre.org/cwe-6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MitreCweContentHistoryType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Submission")]
        public MitreCweMitreCweContentHistoryTypeSubmission Submission { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypeModification> _modification;
        
        [System.Xml.Serialization.XmlElementAttribute("Modification")]
        public System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypeModification> Modification
        {
            get
            {
                return this._modification;
            }
            private set
            {
                this._modification = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModificationSpecified
        {
            get
            {
                return (this.Modification.Count != 0);
            }
        }
        
        public MitreCweContentHistoryType()
        {
            this._modification = new System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypeModification>();
            this._contribution = new System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypeContribution>();
            this._previous_Entry_Name = new System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypePrevious_Entry_Name>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypeContribution> _contribution;
        
        [System.Xml.Serialization.XmlElementAttribute("Contribution")]
        public System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypeContribution> Contribution
        {
            get
            {
                return this._contribution;
            }
            private set
            {
                this._contribution = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContributionSpecified
        {
            get
            {
                return (this.Contribution.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypePrevious_Entry_Name> _previous_Entry_Name;
        
        [System.Xml.Serialization.XmlElementAttribute("Previous_Entry_Name")]
        public System.Collections.Generic.List<MitreCweMitreCweContentHistoryTypePrevious_Entry_Name> Previous_Entry_Name
        {
            get
            {
                return this._previous_Entry_Name;
            }
            private set
            {
                this._previous_Entry_Name = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Previous_Entry_NameSpecified
        {
            get
            {
                return (this.Previous_Entry_Name.Count != 0);
            }
        }
    }
}
