//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FunctionalAreaEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCweFunctionalAreaEnumeration
    {
        
        Authentication,
        
        Authorization,
        
        [System.Xml.Serialization.XmlEnumAttribute("Code Libraries")]
        Code_Libraries,
        
        Counters,
        
        Cryptography,
        
        [System.Xml.Serialization.XmlEnumAttribute("Error Handling")]
        Error_Handling,
        
        [System.Xml.Serialization.XmlEnumAttribute("Interprocess Communication")]
        Interprocess_Communication,
        
        [System.Xml.Serialization.XmlEnumAttribute("File Processing")]
        File_Processing,
        
        Logging,
        
        [System.Xml.Serialization.XmlEnumAttribute("Memory Management")]
        Memory_Management,
        
        Networking,
        
        [System.Xml.Serialization.XmlEnumAttribute("Number Processing")]
        Number_Processing,
        
        [System.Xml.Serialization.XmlEnumAttribute("Program Invocation")]
        Program_Invocation,
        
        [System.Xml.Serialization.XmlEnumAttribute("Protection Mechanism")]
        Protection_Mechanism,
        
        [System.Xml.Serialization.XmlEnumAttribute("Session Management")]
        Session_Management,
        
        Signals,
        
        [System.Xml.Serialization.XmlEnumAttribute("String Processing")]
        String_Processing,
        
        [System.Xml.Serialization.XmlEnumAttribute("Functional-Area-Independent")]
        Functional_Area_Independent,
        
        Power,
        
        Clock,
    }
}
