//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Weakness_Catalog", Namespace="http://cwe.mitre.org/cwe-6", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Weakness_Catalog", Namespace="http://cwe.mitre.org/cwe-6")]
    public partial class MitreCweWeakness_Catalog
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweWeaknessType> _weaknesses;
        
        [System.Xml.Serialization.XmlArrayAttribute("Weaknesses")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Weakness", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweWeaknessType> Weaknesses
        {
            get
            {
                return this._weaknesses;
            }
            private set
            {
                this._weaknesses = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeaknessesSpecified
        {
            get
            {
                return (this.Weaknesses.Count != 0);
            }
        }
        
        public MitreCweWeakness_Catalog()
        {
            this._weaknesses = new System.Collections.Generic.List<MitreCweWeaknessType>();
            this._categories = new System.Collections.Generic.List<MitreCweCategoryType>();
            this._views = new System.Collections.Generic.List<MitreCweViewType>();
            this._external_References = new System.Collections.Generic.List<MitreCweExternalReferenceType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweCategoryType> _categories;
        
        [System.Xml.Serialization.XmlArrayAttribute("Categories")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Category", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweCategoryType> Categories
        {
            get
            {
                return this._categories;
            }
            private set
            {
                this._categories = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoriesSpecified
        {
            get
            {
                return (this.Categories.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweViewType> _views;
        
        [System.Xml.Serialization.XmlArrayAttribute("Views")]
        [System.Xml.Serialization.XmlArrayItemAttribute("View", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweViewType> Views
        {
            get
            {
                return this._views;
            }
            private set
            {
                this._views = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ViewsSpecified
        {
            get
            {
                return (this.Views.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweExternalReferenceType> _external_References;
        
        [System.Xml.Serialization.XmlArrayAttribute("External_References")]
        [System.Xml.Serialization.XmlArrayItemAttribute("External_Reference", Namespace="http://cwe.mitre.org/cwe-6")]
        public System.Collections.Generic.List<MitreCweExternalReferenceType> External_References
        {
            get
            {
                return this._external_References;
            }
            private set
            {
                this._external_References = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool External_ReferencesSpecified
        {
            get
            {
                return (this.External_References.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Version")]
        public string Version { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Date", DataType="date")]
        public System.DateTime Date { get; set; }
    }
}
