//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MitreCweCommonConsequencesTypeConsequence", Namespace="http://cwe.mitre.org/cwe-6", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MitreCweMitreCweCommonConsequencesTypeConsequence
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweScopeEnumeration> _scope;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Scope")]
        public System.Collections.Generic.List<MitreCweScopeEnumeration> Scope
        {
            get
            {
                return this._scope;
            }
            private set
            {
                this._scope = value;
            }
        }
        
        public MitreCweMitreCweCommonConsequencesTypeConsequence()
        {
            this._scope = new System.Collections.Generic.List<MitreCweScopeEnumeration>();
            this._impact = new System.Collections.Generic.List<MitreCweTechnicalImpactEnumeration>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweTechnicalImpactEnumeration> _impact;
        
        [System.Xml.Serialization.XmlElementAttribute("Impact")]
        public System.Collections.Generic.List<MitreCweTechnicalImpactEnumeration> Impact
        {
            get
            {
                return this._impact;
            }
            private set
            {
                this._impact = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImpactSpecified
        {
            get
            {
                return (this.Impact.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Likelihood")]
        public MitreCweLikelihoodEnumeration Likelihood { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LikelihoodSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Note")]
        public MitreCweStructuredTextType Note { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Consequence_ID")]
        public string Consequence_ID { get; set; }
    }
}
