//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RelationshipsType", Namespace="http://cwe.mitre.org/cwe-6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MitreCweRelationshipsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMemberType> _member_Of;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Member_Of")]
        public System.Collections.Generic.List<MitreCweMemberType> Member_Of
        {
            get
            {
                return this._member_Of;
            }
            private set
            {
                this._member_Of = value;
            }
        }
        
        public MitreCweRelationshipsType()
        {
            this._member_Of = new System.Collections.Generic.List<MitreCweMemberType>();
            this._has_Member = new System.Collections.Generic.List<MitreCweMemberType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCweMemberType> _has_Member;
        
        [System.Xml.Serialization.XmlElementAttribute("Has_Member")]
        public System.Collections.Generic.List<MitreCweMemberType> Has_Member
        {
            get
            {
                return this._has_Member;
            }
            private set
            {
                this._has_Member = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Has_MemberSpecified
        {
            get
            {
                return (this.Has_Member.Count != 0);
            }
        }
    }
}
