//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TaxonomyNameEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCweTaxonomyNameEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("7 Pernicious Kingdoms")]
        Item7_Pernicious_Kingdoms,
        
        [System.Xml.Serialization.XmlEnumAttribute("19 Deadly Sins")]
        Item19_Deadly_Sins,
        
        Aslam,
        
        Bishop,
        
        CLASP,
        
        Landwehr,
        
        [System.Xml.Serialization.XmlEnumAttribute("OMG ASCSM")]
        OMG_ASCSM,
        
        [System.Xml.Serialization.XmlEnumAttribute("OMG ASCRM")]
        OMG_ASCRM,
        
        [System.Xml.Serialization.XmlEnumAttribute("OMG ASCMM")]
        OMG_ASCMM,
        
        [System.Xml.Serialization.XmlEnumAttribute("OMG ASCPEM")]
        OMG_ASCPEM,
        
        [System.Xml.Serialization.XmlEnumAttribute("OWASP Top Ten 2004")]
        OWASP_Top_Ten_2004,
        
        [System.Xml.Serialization.XmlEnumAttribute("OWASP Top Ten 2007")]
        OWASP_Top_Ten_2007,
        
        [System.Xml.Serialization.XmlEnumAttribute("OWASP Top Ten")]
        OWASP_Top_Ten,
        
        PLOVER,
        
        [System.Xml.Serialization.XmlEnumAttribute("Protection Analysis")]
        Protection_Analysis,
        
        RISOS,
        
        [System.Xml.Serialization.XmlEnumAttribute("Weber, Karger, Paradkar")]
        WeberComma_KargerComma_Paradkar,
        
        WASC,
        
        [System.Xml.Serialization.XmlEnumAttribute("CERT C Secure Coding")]
        CERT_C_Secure_Coding,
        
        [System.Xml.Serialization.XmlEnumAttribute("CERT C++ Secure Coding")]
        CERT_CPlusPlus_Secure_Coding,
        
        [System.Xml.Serialization.XmlEnumAttribute("The CERT Oracle Secure Coding Standard for Java (2011)")]
        The_CERT_Oracle_Secure_Coding_Standard_For_Java_LeftParenthesis2011RightParenthesis,
        
        [System.Xml.Serialization.XmlEnumAttribute("SEI CERT C Coding Standard")]
        SEI_CERT_C_Coding_Standard,
        
        [System.Xml.Serialization.XmlEnumAttribute("SEI CERT C++ Coding Standard")]
        SEI_CERT_CPlusPlus_Coding_Standard,
        
        [System.Xml.Serialization.XmlEnumAttribute("SEI CERT Oracle Coding Standard for Java")]
        SEI_CERT_Oracle_Coding_Standard_For_Java,
        
        [System.Xml.Serialization.XmlEnumAttribute("SEI CERT Perl Coding Standard")]
        SEI_CERT_Perl_Coding_Standard,
        
        [System.Xml.Serialization.XmlEnumAttribute("Software Fault Patterns")]
        Software_Fault_Patterns,
    }
}
