//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MitreCwePotentialMitigationsTypeMitigation", Namespace="http://cwe.mitre.org/cwe-6", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MitreCweMitreCwePotentialMitigationsTypeMitigation
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<MitreCwePhaseEnumeration> _phase;
        
        [System.Xml.Serialization.XmlElementAttribute("Phase")]
        public System.Collections.Generic.List<MitreCwePhaseEnumeration> Phase
        {
            get
            {
                return this._phase;
            }
            private set
            {
                this._phase = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PhaseSpecified
        {
            get
            {
                return (this.Phase.Count != 0);
            }
        }
        
        public MitreCweMitreCwePotentialMitigationsTypeMitigation()
        {
            this._phase = new System.Collections.Generic.List<MitreCwePhaseEnumeration>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Strategy")]
        public MitreCweMitigationStrategyEnumeration Strategy { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StrategySpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public MitreCweStructuredTextType Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Effectiveness")]
        public MitreCweEffectivenessEnumeration Effectiveness { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectivenessSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Effectiveness_Notes")]
        public MitreCweStructuredTextType Effectiveness_Notes { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Mitigation_ID")]
        public string Mitigation_ID { get; set; }
    }
}
