//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OperatingSystemNameEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCweOperatingSystemNameEnumeration
    {
        
        AIX,
        
        Android,
        
        [System.Xml.Serialization.XmlEnumAttribute("BlackBerry OS")]
        BlackBerry_OS,
        
        [System.Xml.Serialization.XmlEnumAttribute("Chrome OS")]
        Chrome_OS,
        
        Darwin,
        
        FreeBSD,
        
        [System.Xml.Serialization.XmlEnumAttribute("iOS")]
        IOS,
        
        [System.Xml.Serialization.XmlEnumAttribute("macOS")]
        MacOS,
        
        NetBSD,
        
        OpenBSD,
        
        [System.Xml.Serialization.XmlEnumAttribute("Red Hat")]
        Red_Hat,
        
        Solaris,
        
        SUSE,
        
        [System.Xml.Serialization.XmlEnumAttribute("tvOS")]
        TvOS,
        
        Ubuntu,
        
        [System.Xml.Serialization.XmlEnumAttribute("watchOS")]
        WatchOS,
        
        [System.Xml.Serialization.XmlEnumAttribute("Windows 9x")]
        Windows_9X,
        
        [System.Xml.Serialization.XmlEnumAttribute("Windows Embedded")]
        Windows_Embedded,
        
        [System.Xml.Serialization.XmlEnumAttribute("Windows NT")]
        Windows_NT,
    }
}
