//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StakeholderEnumeration", Namespace="http://cwe.mitre.org/cwe-6")]
    public enum MitreCweStakeholderEnumeration
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("Academic Researchers")]
        Academic_Researchers,
        
        [System.Xml.Serialization.XmlEnumAttribute("Applied Researchers")]
        Applied_Researchers,
        
        [System.Xml.Serialization.XmlEnumAttribute("Assessment Teams")]
        Assessment_Teams,
        
        [System.Xml.Serialization.XmlEnumAttribute("Assessment Tool Vendors")]
        Assessment_Tool_Vendors,
        
        [System.Xml.Serialization.XmlEnumAttribute("CWE Team")]
        CWE_Team,
        
        Educators,
        
        [System.Xml.Serialization.XmlEnumAttribute("Hardware Designers")]
        Hardware_Designers,
        
        [System.Xml.Serialization.XmlEnumAttribute("Information Providers")]
        Information_Providers,
        
        [System.Xml.Serialization.XmlEnumAttribute("Product Customers")]
        Product_Customers,
        
        [System.Xml.Serialization.XmlEnumAttribute("Product Vendors")]
        Product_Vendors,
        
        [System.Xml.Serialization.XmlEnumAttribute("Software Developers")]
        Software_Developers,
        
        [System.Xml.Serialization.XmlEnumAttribute("Vulnerability Analysts")]
        Vulnerability_Analysts,
        
        Other,
    }
}
