//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.631.0 using the following command:
// xscgen cwe_schema_latest.xsd --namespace=http://cwe.mitre.org/cwe-6=Vulns.Fetchers.Dtos --output=./out/ --disableComments --separateFiles --uniqueTypeNames --netCore --verbose --collectionType=System.Collections.Generic.IList`1 --collectionImplementationType=System.Collections.Generic.List`1 --generatedCodeAttribute=false --description=false --disableComments
namespace Vulns.Jobs.Weaknesses
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.631.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExternalReferenceType", Namespace="http://cwe.mitre.org/cwe-6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MitreCweExternalReferenceType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<string> _author;
        
        [System.Xml.Serialization.XmlElementAttribute("Author")]
        public System.Collections.Generic.List<string> Author
        {
            get
            {
                return this._author;
            }
            private set
            {
                this._author = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthorSpecified
        {
            get
            {
                return (this.Author.Count != 0);
            }
        }
        
        public MitreCweExternalReferenceType()
        {
            this._author = new System.Collections.Generic.List<string>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Title")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Edition")]
        public string Edition { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Publication")]
        public string Publication { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Publication_Year")]
        public string Publication_Year { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Publication_Month")]
        public string Publication_Month { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Publication_Day")]
        public string Publication_Day { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Publisher")]
        public string Publisher { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string URL { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("URL_Date", DataType="date")]
        public System.DateTime URL_Date { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool URL_DateSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Reference_ID")]
        public string Reference_ID { get; set; }
    }
}
